name: Generate Contribution Gravity

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gravity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: flycran/github-gravity@v1
        with:
          username: ${{ github.repository_owner }}
          text: Aashish Yadav
          shape: square
          background-color: transparent
          text-color: "#39D353"
          output-path: gravity.svg
      - name: Rescale animation to loop every 4 seconds
        run: python3 rescale_gravity.py gravity.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gravity.svg
          if git commit -m "update gravity contribution graphic"; then git push; fi
